spring.application.name=travelmate-backend
server.port=8080

spring.data.mongodb.uri=mongodb+srv://pythonprogram010_db_user:TravelMate123@travelmate-cluster.h95bnjm.mongodb.net/travelmate?retryWrites=true&w=majority&appName=travelmate-cluster
